const STARTING_MINUTES_IN_HOUR = 0;
const ENDING_MINUTES_IN_HOUR = 59;
const STARTING_HOURS_IN_DAY = 0;
const ENDING_HOURS_IN_DAY = 23;
const STARTING_DAYS_IN_MONTH = 1;
const ENDING_DAYS_IN_MONTH = 31;
const STARTING_MONTHS_IN_YEAR = 1;
const ENDING_MONTHS_IN_YEAR = 12;
const STARTING_DAYS_IN_WEEK = 0;
const ENDING_DAYS_IN_WEEK = 6;

module.exports = {
    STARTING_MINUTES_IN_HOUR,
    ENDING_MINUTES_IN_HOUR,
    STARTING_HOURS_IN_DAY,
    ENDING_HOURS_IN_DAY,
    STARTING_DAYS_IN_MONTH,
    ENDING_DAYS_IN_MONTH,
    STARTING_MONTHS_IN_YEAR,
    ENDING_MONTHS_IN_YEAR,
    STARTING_DAYS_IN_WEEK,
    ENDING_DAYS_IN_WEEK
};
